In [83]:
import numpy as np

In [84]:
years_of_experience = np.array([1, 2, 3, 4, 5])

In [85]:
# lets add 1 more year to this
years_of_experience_plusone = years_of_experience + 1
years_of_experience_plusone

array([2, 3, 4, 5, 6])

In [86]:
# select fourth and fifth year of experience
years_of_experience[3:5]

array([4, 5])

In [87]:
# now lets try to get years of experience with more than 2 years
more_than_two_exp = years_of_experience[years_of_experience > 2]
more_than_two_exp

array([3, 4, 5])

In [88]:
# lets import random library
import random

In [89]:
salary = [random.randint(90000, 180000) for num in range(100)]

In [90]:
salary

[168383,
 104146,
 140643,
 102806,
 165531,
 174403,
 140392,
 147275,
 176858,
 174343,
 116567,
 127928,
 164416,
 154658,
 118936,
 145878,
 149988,
 141838,
 136646,
 172751,
 153074,
 169882,
 156563,
 118165,
 109596,
 134465,
 174457,
 116193,
 111282,
 144963,
 130046,
 151015,
 147026,
 131582,
 146299,
 139418,
 175913,
 120733,
 162747,
 117120,
 144447,
 146475,
 145059,
 102047,
 92531,
 108508,
 158870,
 158209,
 151164,
 107434,
 139089,
 109652,
 110825,
 155734,
 95018,
 143564,
 90180,
 139779,
 168195,
 116450,
 109725,
 164388,
 101116,
 175902,
 133422,
 97910,
 118984,
 124188,
 175628,
 160885,
 133811,
 106961,
 140970,
 148600,
 120674,
 129288,
 162629,
 145885,
 131404,
 138569,
 102648,
 176100,
 155671,
 173631,
 137476,
 120800,
 105545,
 101165,
 152799,
 162360,
 147293,
 157263,
 169501,
 132413,
 101284,
 137345,
 133078,
 134808,
 132776,
 161098]

In [91]:
# lets convert this to numpy array
salary_array = np.array(salary)
salary_array

array([168383, 104146, 140643, 102806, 165531, 174403, 140392, 147275,
       176858, 174343, 116567, 127928, 164416, 154658, 118936, 145878,
       149988, 141838, 136646, 172751, 153074, 169882, 156563, 118165,
       109596, 134465, 174457, 116193, 111282, 144963, 130046, 151015,
       147026, 131582, 146299, 139418, 175913, 120733, 162747, 117120,
       144447, 146475, 145059, 102047,  92531, 108508, 158870, 158209,
       151164, 107434, 139089, 109652, 110825, 155734,  95018, 143564,
        90180, 139779, 168195, 116450, 109725, 164388, 101116, 175902,
       133422,  97910, 118984, 124188, 175628, 160885, 133811, 106961,
       140970, 148600, 120674, 129288, 162629, 145885, 131404, 138569,
       102648, 176100, 155671, 173631, 137476, 120800, 105545, 101165,
       152799, 162360, 147293, 157263, 169501, 132413, 101284, 137345,
       133078, 134808, 132776, 161098])

In [92]:
# lets sum all
# %%timeit
salary_array_sum = np.sum(salary_array)
salary_array_sum

np.int64(13834148)

In [93]:
# lets sum all
# %%timeit
salary_array_sum_2 = sum(salary_array)

In [94]:
# multiply using np library
salary_array_multiply = np.prod(salary_array)
salary_array_multiply

np.int64(0)

In [95]:
# now lets calculate mean as well
salary_array_mean = np.mean(salary_array)
salary_array_mean


np.float64(138341.48)

In [96]:
# now lets calculate variation within array
salary_array_var = np.var(salary_array)
salary_array_var

np.float64(557935557.7096001)

In [97]:
# lets find the minimum value
salary_array_min = np.min(salary_array)
salary_array_min

np.int64(90180)

In [98]:
# max value
salary_array_max = np.max(salary_array)
salary_array_max

np.int64(176858)

In [101]:
list_format = [168383, 104146, 140643, 102806, 165531, 174403, 140392, 147275,
       176858, 174343, np.nan, 127928, 164416, 154658, np.nan, 145878,
       149988, 141838, 136646, 172751, 153074, 169882, 156563, 118165,
       109596, 134465, 174457, 116193, 111282, 144963, 130046, 151015,
       147026, 131582, np.nan, 139418, 175913, 120733, 162747, 117120,
       144447, 146475, 145059, np.nan,  np.nan, 108508, 158870, 158209,
       151164, 107434, 139089, 109652, 110825, 155734,  95018, 143564,
        90180, 139779, 168195, 116450, 109725, 164388, 101116, 175902,
       133422,  97910, 118984, 124188, 175628, 160885, 133811, 106961,
       140970, np.nan, 120674, 129288, 162629, 145885, 131404, 138569,
       102648, 176100, 155671, 173631, np.nan, 120800, np.nan, 101165,
       152799, 162360, 147293, 157263, 169501, 132413, 101284, 137345,
       133078, 134808, 132776, 161098]

In [104]:
# now lets calculate the median of list_format, excluding NaNs
list_format_array = np.array(list_format)
list_format_no_nan = list_format_array[~np.isnan(list_format_array)]
list_format_median = np.median(list_format_no_nan)
list_format_median

np.float64(140806.5)

In [107]:
# i want to count the number of salary which ranges from 110000 to 130000
salary_count = np.count_nonzero((salary_array >= 110000) & (salary_array <= 130000))
salary_count

15

In [108]:
# i want to count total blank values in the list
blank_values_count = np.count_nonzero(np.isnan(list_format_array))
blank_values_count

8